// Vocabulary recorded from the verified Grok controlled-runtime corpus (installed
// Grok 1.0.25 and 1.0.30 captures, every registered scenario), for deriving
// shareable fixtures from private exact captures.
//
// WHY an allowlist and not a denylist: a denylist of secrets cannot know the
// prompts, paths, hostnames or future native fields in a capture. Only names and
// values listed here pass through; everything else becomes structure (`field_N`,
// `[text N]`, identity ordinals). Same principle as normalizeTranscript.
//
// WHY recorded rather than guessed: these are exactly the key names observed on
// the wire, in harness records and in native updates/events rows, minus dynamic
// keys that carry content (question texts, model-specific usage keys, fixture
// map keys). A new native version that adds fields shows up as a nonzero
// `unknownKeys` count in the derived manifest; extend this file deliberately,
// never by bulk-copying a new survey.
//
// WHY enums are per key and short: only protocol discriminators are listed.
// Free-text fields (commands, errors, previews, summaries, prompts), credential
// headers, hostnames, ports and timestamps are deliberately absent even where
// the recorded values happened to be harmless fixture text.

export const RECORDED_PROTOCOL_KEYS: ReadonlySet<string> = new Set([
  // Harness terminal checkpoint key; the corpus survey skipped terminal events,
  // whose only other kept fields are the numeric geometry keys listed below.
  "frame",
  // Native fields first recorded by the terminal-initiated `/new` scenario: the
  // TUI's own `_x.ai/commands/list` result and a native log context.
  "commands", "sources", "mcp_server_count",
  // Verification record fields of the prompt-identity, queued-cancel and
  // terminal new-session scenarios. Names only; their values still pass through
  // the normal value rules.
  "adoptedAsQueueEntry", "adoptedAsRunning", "adoptedAsCompleted", "adoptedInResult", "queueNotifications", "completionNotifications",
  "runningOutcome", "queuedOutcome", "queuedInferenceObserved", "runningSettledBeforeCancel", "queueAtCancel",
  "runningReportedWithClientId", "queuedEntryUsesClientId",
  "terminalRequestedNewSession", "terminalShowsOtherSession", "newSessionAnnouncedToControl",
  "originalUpdatesToTerminalBeforePrompt", "originalUpdatesToTerminalDuringPrompt", "otherSessionUpdatesToTerminal",
  "terminalDrewOriginalReply", "originalPromptOutcome",
  "Content", "EditsApplied", "Entered", "Error", "FileContent", "ImageContent", "Ok", "OkayOutput",
  "PlanReady", "TodosUpdated", "UserAnswered", "_meta", "absolute_path", "absolute_root_path", "acpOutcome",
  "actionId", "action_registered", "activity", "added", "agentAddress", "agentCapabilities", "agentId",
  "agentInstanceId", "agentName", "agentProfile", "agentResult", "agentTimestampMs", "agentType",
  "agentVersion", "agents", "annotations", "answers", "apiBackend", "apiDurationMs", "arguments",
  "arguments_delta", "arm_via", "ask_user", "attached", "attempt_id", "audio", "auth", "authMethods",
  "auth_required", "auth_retry_attempted", "autoCompactThresholdPercent", "autoMode", "auto_mode",
  "availableCommands", "availableModels", "background", "binary", "blocked_ms", "blockingEvents",
  "bothInferenceInputsObserved", "byteOffset", "cacheCreationTokens", "cache_creation_input_tokens",
  "cache_read_input_tokens", "cachedReadTokens", "callId", "call_id", "cancelRewind", "cancellationCategory",
  "cancellationContext", "cancellation_category", "cancellation_context", "capabilities", "category",
  "checkpoint_file", "checkpoint_id", "child_session_id", "choice", "chunkId", "claims", "clean_files",
  "clientCapabilities", "clientInfo", "clientType", "clientVersion", "client_id", "client_state",
  "client_type", "client_version", "clipboardIsolated", "close", "code", "code_nav_enabled",
  "codebaseIndexed", "cols", "command", "commandsCount", "compactionCount", "complete", "completionObserved",
  "compressed_bytes", "compressed_height", "compressed_width", "configOptions", "conflicts", "connected",
  "connectionId", "content", "content_concise", "context", "context_after", "context_before", "control_v1",
  "conversation_message_count", "count", "cpu_profile_active", "cpu_profile_stopping", "created_at", "ctx",
  "currentModeId", "currentModelId", "currentValue", "currentWorkingDirectory", "current_dir",
  "cursorPaintGeneration", "cursor_worker", "cwd", "data", "decision", "decisions", "defaultAuthMethodId",
  "default_model", "description", "detail", "details", "directory", "disabled", "duration_ms", "edits",
  "effective_context_source", "elapsedMs", "elapsed_ms", "embeddedContext", "enabled", "entries", "epoch",
  "error", "eventId", "exitCode", "exit_code", "exit_plan", "expected", "failed", "feedback",
  "feedbackEnabled", "feedbackTraceOffer", "file", "file_matches", "file_path", "filter_session_id",
  "finished", "first_method", "force", "freeTokens", "from", "from_default_auth_method_id", "fs", "fs_read",
  "fs_write", "generation", "gitRoot", "glob", "grace_ms", "grokShell", "guardState", "hasCache",
  "has_file_changes", "headerPolicy", "headers", "healthy", "height", "hint", "home", "hostname", "http",
  "id", "identityHeaders", "image", "image_url", "images", "independentlyVerified", "index",
  "inferenceObserved", "inferenceRequests", "injected", "input", "inputTokens", "input_tokens", "isError",
  "isGitRepo", "isReplay", "isWorktree", "is_background", "is_error", "is_reinit", "is_timeout", "jsonrpc",
  "key", "kind", "label", "lastChangeUnixMs", "layoutEpoch", "layoutStartGeneration", "leaderAlive",
  "leader_binary_version", "leader_capabilities", "leader_protocol_version", "len", "limit",
  "lineStartOffset", "line_number", "line_prefix", "list", "loadObserved", "loadSession", "locations",
  "lock_path", "loop_index", "lvl", "match_count", "matches", "mcpApps", "mcpCapabilities", "mcpServers",
  "mcpToolCount", "merge", "message", "messageCount", "messageTokens", "metadata", "method", "methodId",
  "method_id", "methods_count", "mimeType", "mime_type", "mode", "model", "modelCalls", "modelDisplayName",
  "modelFingerprint", "modelId", "modelState", "modelUsage", "model_id", "models", "msg", "multiSelect",
  "multi_select", "multiline", "name", "names", "namespace", "nativeExitCode", "nativeSignal",
  "nativeVersion", "newText", "new_line", "new_string", "nodeVersion", "note", "notes", "numTurns",
  "num_file_snapshots", "observed", "offset", "ok", "oldText", "old_line", "old_string", "optionId",
  "options", "order", "origin", "original_bytes", "original_height", "original_width", "outcome", "output",
  "outputKind", "outputTokens", "output_file", "output_for_prompt", "output_tokens", "params",
  "parent_prompt_id", "parent_session_id", "path", "pattern", "payload", "payloads_queued",
  "payloads_written", "permission", "personas", "phase", "phase_elapsed_ms", "pid", "planContent",
  "planSteps", "plan_content", "plan_file_path", "plan_file_seed", "position", "preview",
  "previousLeaderAbsent", "previousLeaderPid", "previousTuiAbsent", "previousTuiPid", "primarySessionId",
  "priority", "processAbsent", "profile", "profile_formats", "profile_started_at", "profiling_compiled_in",
  "profiling_supported", "prompt", "promptCapabilities", "promptId", "promptIndex", "prompt_id",
  "prompt_index", "prompt_index_at_compaction", "prompt_len", "prompt_preview", "prompt_text", "prompts",
  "properties", "protocolVersion", "providerLayoutEpoch", "query", "question", "questions", "rawInput",
  "rawOutput", "raw_output", "readTextFile", "read_only", "ready", "reason", "reasoningTokens",
  "reasoning_tokens", "reconnect_attempted", "redirect_kind", "refreshed", "rejected", "relaunch_v1",
  "remaining_in_queue", "removed", "removed_from_queue", "replace_all", "replayObserved", "requestId",
  "request_id", "resident", "resolvedModelId", "resource", "restored", "result", "result_count", "resume",
  "resume_from_hint", "resumedLeaderPid", "resumedTuiPid", "retained", "reverted_files", "rewind_points",
  "role", "roles", "rows", "rpcCode", "run_in_background", "runningKind", "runningPromptId", "runningText",
  "runtime_cpu_profile", "schema", "schema_version", "screenMode", "secondSessionId", "selected",
  "send_now_cancel", "server", "serverUrl", "server_name", "servers", "session", "sessionCapabilities",
  "sessionId", "sessionRecap", "sessionUpdate", "session_id", "session_relationship", "session_summary",
  "shortcut", "showModelFingerprint", "showNonGitWarning", "sid", "signal", "skills", "slash_command",
  "snapshotByteLength", "socket_path", "source", "src", "sse", "stable", "staleCallRejected", "staleError",
  "staleReplyRejected", "state", "status", "status_line", "stderr", "stdout", "stopReason", "stopSignals",
  "stop_reason", "streamStartMs", "subagentBackground", "subagent_id", "subagent_type", "succeeded",
  "success", "summary", "summary_for_prompt", "summary_preview", "systemPromptTokens", "target",
  "target_directory", "target_file", "target_prompt_index", "task", "task_id", "tasks", "terminal", "text",
  "timed_out", "timeout_sec", "timestamp", "title", "to", "todos", "token", "tokens", "tokens_after",
  "tokens_before", "tokens_used", "tool", "toolCall", "toolCallCount", "toolCallId", "toolDefinitionsCount",
  "toolDefinitionsTokens", "toolOverrides", "tool_call_id", "tool_calls", "tool_count", "tool_hints",
  "tool_index", "tool_input", "tool_name", "tool_output_for_prompt", "tool_output_for_prompt_concise",
  "tools", "total", "totalContextTokens", "totalTokens", "total_bytes", "total_lines", "total_servers",
  "total_tools", "traceparent", "transport", "truncated", "ts", "ttfa_ms", "turn", "turnCount", "turnIndex",
  "turnStartMs", "turn_number", "turns", "type", "ui_config_field", "uncertain", "update", "updateParams",
  "updateType", "upserted", "uri", "url", "usage", "usageCategories", "usagePct", "used", "user_context",
  "user_message_echo", "value", "variant", "ver", "version", "voiceMode", "wait_ms", "waited_ms",
  "was_bare_echo", "was_cancelling", "width", "will_wake", "wire_prompt_id", "workflowPath",
  "workflowSource", "workspace_exposure", "worktree_path", "writeId", "writeTextFile", "ws_url_suffix",
  "x-grok-client-version", "x-grok-req-id", "x-grok-session-id", "x-grok-turn-idx", "x.ai/bashOutputNoColor",
  "x.ai/capabilities", "x.ai/fs_notify", "x.ai/gitHeadChanged", "x.ai/hooks", "x.ai/hunkTracker",
  "x.ai/incrementalBashOutput", "x.ai/leaderClientId", "x.ai/mcp/sdk", "x.ai/memoryMode", "x.ai/pluginDirs",
  "x.ai/sessionConfig", "x.ai/sessionDetail", "x.ai/statusLine", "x.ai/tool", "x.ai/userMessageEcho",
  "x_keyword_search", "x_semantic_search", "x_thread_fetch", "x_user_search", "xaiAcpChannelFailure", "yolo",
  "yoloMode", "yolo_mode",
])

export const RECORDED_ENUM_VALUES: Readonly<Record<string, ReadonlySet<string>>> = {
  "activity": new Set(["idle", "thinking", "working", "writing_tool_call"]),
  "agentName": new Set(["grok-build-plan"]),
  "agentProfile": new Set(["grok-build-plan"]),
  "agentType": new Set(["grok-build-plan"]),
  "apiBackend": new Set(["Responses"]),
  "arm_via": new Set(["exact"]),
  "ask_user": new Set(["ask_user_question"]),
  "cancellationCategory": new Set(["MidTurnAbort", "PermissionCancelled", "PermissionRejected"]),
  "cancellation_category": new Set(["mid_turn_abort", "permission_cancelled", "permission_rejected"]),
  "category": new Set(["model"]),
  "choice": new Set(["allow-once", "reject-once"]),
  "client_state": new Set(["ready"]),
  "client_type": new Set(["grok-code-headless", "grok-shell"]),
  "clientType": new Set(["grok-pager"]),
  "code": new Set(["FS_NOT_FOUND", "closed", "remote", "stale-request"]),
  "context": new Set(["scrollback_focused_only"]),
  "currentModeId": new Set(["default", "plan"]),
  "currentModelId": new Set(["grok-4.6"]),
  "currentValue": new Set(["grok-4.6"]),
  "decision": new Set(["allow", "cancelled", "deny"]),
  "defaultAuthMethodId": new Set(["xai.api_key"]),
  "effective_context_source": new Set(["new"]),
  "exit_plan": new Set(["exit_plan_mode"]),
  "file": new Set(["chat_history.jsonl", "events.jsonl", "summary.json", "updates.jsonl"]),
  "first_method": new Set(["xai.api_key"]),
  "from": new Set(["responding", "thinking", "tool_running", "waiting_model", "waiting_subagent", "writing_tool_call"]),
  "guardState": new Set(["holding"]),
  "headerPolicy": new Set(["credentials excluded"]),
  "jsonrpc": new Set(["2.0"]),
  "kind": new Set(["Other", "allow_always", "allow_once", "ask_user", "build", "closed", "closing", "edit", "enter_plan", "execute", "exit_plan", "exited", "hold", "list", "local", "opened", "other", "permission", "plan", "plan_approval", "prompt", "question", "read", "received", "reject_always", "reject_once", "search", "search_tool", "spawned", "task", "text", "think", "tool", "use_tool", "write", "write-attempt", "write-complete"]),
  "lvl": new Set(["debug", "info", "warn"]),
  "method": new Set(["GET", "POST", "_x.ai/ask_user_question", "_x.ai/billing", "_x.ai/bundle/status", "_x.ai/commands/list", "_x.ai/compact_conversation", "_x.ai/exit_plan_mode", "_x.ai/log", "_x.ai/marketplace/list", "_x.ai/mcp/call", "_x.ai/mcp/init_progress", "_x.ai/mcp/list", "_x.ai/mcp/server_status", "_x.ai/mcp/servers_updated", "_x.ai/mcp_initialized", "_x.ai/models/update", "_x.ai/prompt_history", "_x.ai/queue/changed", "_x.ai/rewind/execute", "_x.ai/rewind/points", "_x.ai/session/info", "_x.ai/session/prompt_complete", "_x.ai/session/update", "_x.ai/session/update_mcp_servers", "_x.ai/session_notification", "_x.ai/sessions/changed", "authenticate", "initialize", "session/cancel", "session/load", "session/new", "session/prompt", "session/request_permission", "session/update"]),
  "method_id": new Set(["xai.api_key"]),
  "methodId": new Set(["xai.api_key"]),
  "mime_type": new Set(["image/png"]),
  "mimeType": new Set(["image/png", "text/plain"]),
  "mode": new Set(["conversation_only", "default", "off", "stdio"]),
  "model": new Set(["grok-4.6"]),
  "model_id": new Set(["grok-4.6"]),
  "modelDisplayName": new Set(["grok-4.6"]),
  "modelId": new Set(["grok-4.6"]),
  "msg": new Set(["agent response complete", "mouse_reporting_toggle.startup", "pager eager auth method selected", "pager quit", "pager started", "prompt.acked", "prompt.acp_send.done", "prompt.acp_send.start", "prompt.drain", "prompt.enqueue", "prompt.send_server_authoritative", "session.load.done", "session.load.start", "slash.registry.update", "term.writer.blocked", "term.writer.recovered", "turn.complete", "turn.end_reconcile.armed", "turn.end_reconciled_from_broadcast", "turn.first_activity", "turn.phase_transition"]),
  "namespace": new Set(["grok_build", "opencode"]),
  "optionId": new Set(["allow-edits-session", "allow-once", "always-allow", "reject-always", "reject-once"]),
  "order": new Set(["acp-then-tui", "tui-then-acp"]),
  "outcome": new Set(["abandoned", "accepted", "approved", "cancelled", "completed", "error", "selected", "success"]),
  "outputKind": new Set(["string"]),
  "permission": new Set(["allow-once", "cancel", "reject-once"]),
  "phase": new Set(["idle", "mid-turn", "permission_prompt", "streaming_reasoning", "streaming_text", "tool_execution", "waiting_for_model"]),
  "plan_file_seed": new Set(["empty"]),
  "priority": new Set(["medium"]),
  "profile": new Set(["deny-process-fork"]),
  "reason": new Set(["User rejected the execution", "config_added", "config_removed", "initialized", "owner-stopped", "upstream-closed"]),
  "redirect_kind": new Set(["queued_after_cancel"]),
  "role": new Set(["control", "guard-upstream", "tui"]),
  "runningKind": new Set(["prompt"]),
  "screenMode": new Set(["fullscreen"]),
  "server": new Set(["fixture"]),
  "server_name": new Set(["fixture"]),
  "session_relationship": new Set(["primary"]),
  "sessionUpdate": new Set(["agent_message_chunk", "agent_thought_chunk", "auto_compact_completed", "available_commands_update", "background_tasks", "compaction_checkpoint", "current_mode_update", "image_compressed", "image_dropped", "interaction_resolved", "last_turn_summary", "model_changed", "pending_interaction", "plan", "response_completed", "rewind_marker", "session_info_update", "session_summary_generated", "subagent_finished", "subagent_spawned", "tool_call", "tool_call_delta_chunk", "tool_call_update", "turn_completed", "user_message_chunk"]),
  "shortcut": new Set(["Ctrl+R"]),
  "signal": new Set(["SIGKILL", "SIGTERM", "queue_changed"]),
  "source": new Set(["default", "local", "session_update"]),
  "src": new Set(["grok-pager"]),
  "state": new Set(["none"]),
  "status": new Set(["Completed", "Failed", "Pending", "completed", "failed", "fulfilled", "in_progress", "initializing", "pending", "ready", "unavailable"]),
  "stop_reason": new Set(["cancelled", "end_turn"]),
  "stopReason": new Set(["cancelled", "end_turn"]),
  "subagent_type": new Set(["general-purpose"]),
  "task": new Set(["spawn_subagent"]),
  "to": new Set(["responding", "thinking", "tool_running", "waiting_model", "waiting_subagent", "writing_tool_call"]),
  "tool": new Set(["fixture_echo", "fixture_error", "fixture_image", "fixture_mixed", "fixture_structured"]),
  "tool_name": new Set(["ask_user_question", "enter_plan_mode", "exit_plan_mode", "fixture__fixture_echo", "fixture__fixture_error", "fixture__fixture_image", "fixture__fixture_mixed", "fixture__fixture_structured", "fixture_echo", "fixture_error", "fixture_image", "fixture_mixed", "fixture_structured", "grep", "list_dir", "read_file", "run_terminal_command", "search_replace", "search_tool", "spawn_subagent", "todo_write", "use_tool", "write"]),
  "transport": new Set(["http"]),
  "updateType": new Set(["AgentMessageChunk", "AgentThoughtChunk", "AvailableCommandsUpdate", "Plan", "ToolCall", "ToolCallUpdate"]),
  "variant": new Set(["AskUserQuestion", "Bash", "EnterPlanMode", "ExitPlanMode", "Grep", "ListDir", "ReadFile", "SearchReplace", "SearchTool", "Task", "TodoWrite", "UseTool", "Write"]),
  "workflowSource": new Set(["builtin"]),
  "x.ai/memoryMode": new Set(["legacy"]),
  "xaiAcpChannelFailure": new Set(["recv_failed"]),
  // `type` is enumerated rather than pattern-matched: it appears at every depth
  // (envelopes, content blocks, config options, native event rows), and an
  // identifier pattern would also pass model-written or host text that happens
  // to look like an identifier.
  "type": new Set(["AskUserQuestion", "Bash", "EnterPlanMode", "ExitPlanMode", "GrepSearch", "ListDir", "MCP", "ReadFile", "SearchReplace",
    "SearchTool", "SubagentCompleted", "Todo", "acp", "caught-up", "content", "control", "control_result", "diff", "first_token",
    "get_leader_info", "http", "image", "input_image", "input_text", "leader_info", "leader_ready", "loop_started", "mcp_config_resolved",
    "mcp_health_check", "mcp_init_completed", "mcp_server_connected", "mcp_server_starting", "mcp_tool_call_completed", "mcp_tool_call_started",
    "object", "permission_requested", "permission_resolved", "phase_changed", "ping", "pong", "register", "registered", "reset", "resource",
    "resource_link", "select", "stdio", "string", "text", "tool_completed", "tool_started", "turn_ended", "turn_started"]),
}
